name: bip39
description: Production-grade Flutter implementation of Bitcoin BIP39 mnemonic codes
version: 2.0.0
homepage: https://github.com/bulltechnologies/bip39
repository: https://github.com/bulltechnologies/bip39
issue_tracker: https://github.com/bulltechnologies/bip39/issues
license: BSD-3-Clause
publish_to: none

environment:
  sdk: ^3.12.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  native_crypto:
    git:
      url: https://github.com/bulltechnologies/native_crypto.git
      ref: a98a33c7331d07a08f2ea3e8585603c172da7fc7
  unorm_dart: ^0.3.0
  hex: ^0.2.0

flutter:
  assets:
    - test/vectors.json
    - test/japanese_vectors.json

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
